# Uncomment the next line to define a global platform for your project
platform :ios, '9.2'
# platform :ios, '8.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
